FROM golang:1.11.3-alpine3.8 as builder

COPY . .

WORKDIR /go/src/dns/

RUN go build  -o hello-dns

FROM alpine:latest

COPY --from=builder /go/src/dns/hello-dns /usr/local/bin/

EXPOSE 8080
##CMD ["/usr/local/bin/hello-dns"]

ENTRYPOINT ["tail","-f","/dev/null"]
