FROM alpine:latest

RUN apk add -U tzdata mariadb-client mariadb-dev \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && apk del tzdata
    
EXPOSE 8080

ENTRYPOINT ["tail","-f","/dev/null"]
